name: Deploy FastAPI to Ubuntu VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy FastAPI application
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << 'EOF'
          REPO_URL="git@github.com:${{ secrets.REPO_OWNER }}/{{ secrets.REPO_NAME }}.git"
          PROJECT_NAME="{{ secrets.REPO_NAME }}"

          cd ~

          if [ ! -d "$PROJECT_NAME" ]; then
            echo "Repository does not exist. Cloning..."
            git clone $REPO_URL
          else
            echo "Repository exists. Pulling latest changes..."
            cd $PROJECT_NAME
            git pull origin main
          fi

          cd $PROJECT_NAME

          if [ ! -d "venv" ]; then
            python3 -m venv venv
          fi

          source venv/bin/activate

          pip install --upgrade pip
          pip install -r requirements.txt

          PID=$(ps aux | grep "[u]vicorn.*8000" | awk '{print $2}')
          if [ -n "$PID" ]; then
            echo "Killing existing FastAPI server process with PID: $PID"
            kill -9 $PID
            echo "Process killed."
          else
            echo "No process found on port 8000."
          fi

          MUL_PROC_PIDS=$(ps aux | grep "[m]ultiprocessing.spawn" | awk '{print $2}')
          if [ -n "$MUL_PROC_PIDS" ]; then
            echo "Killing existing multiprocessing processes with PIDs: $MUL_PROC_PIDS"
            kill -9 $MUL_PROC_PIDS
            echo "Multiprocessing processes killed."
          else
            echo "No multiprocessing processes found."
          fi
          
          nohup uvicorn main:app --host 0.0.0.0 --port 8000 > nohup.out 2>&1 & disown

          echo "FastAPI application deployed and running."

          exit 0
        EOF
