name: Deploy FastAPI App via Public VM to Private VM

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest 

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up SSH agent for public VM
      - name: Set up SSH agent for public VM
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PUBLIC_VM_KEY }}  # Private key for the public VM

      # Run Deployment Script on Private VM via Public VM
      - name: Run Deployment Script on Private VM via Public VM
        run: |
          # First, SSH into the public VM
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_PUBLIC_VM_USER }}@${{ secrets.SSH_PUBLIC_VM_IP }} << 'EOF'
            # Inside the public VM, set up the SSH agent for the private VM
            eval "$(ssh-agent -s)"  # Start the SSH agent
            echo '${{ secrets.SSH_PRIVATE_VM_KEY }}' | ssh-add -  # Add the private VM key
            
            # Now SSH into the private VM and run the script
            ssh -A ${{ secrets.SSH_PRIVATE_VM_USER }}@${{ secrets.SSH_PRIVATE_VM_IP }} 'nohup /path/to/script.sh > /dev/null 2>&1 &'
          EOF
          
          # Exit immediately to prevent GitHub Actions from waiting for the script to finish
          exit 0
